name: Run JAX Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install JAX and JAXlib
      run: |
        python -m pip install --upgrade pip
        pip install jax jaxlib

    - name: Run JAX XLA test
      run: python jax-xla.py

    - name: Run JAX PJRT CPU test
      run: python jax-pjrt-cpu.py

    - name: Install JAX-Metal
      run: |
        pip install jax-metal

    - name: Run JAX PJRT Metal test
      run: python jax-pjrt-cpu-metal.py
